# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sat May 18 07:04:00 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(760, 701)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.widgetMain = QtGui.QWidget(MainWindow)
        self.widgetMain.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMain.sizePolicy().hasHeightForWidth())
        self.widgetMain.setSizePolicy(sizePolicy)
        self.widgetMain.setObjectName(_fromUtf8("widgetMain"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widgetMain)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(9, 4, 9, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBoxAccount = QtGui.QGroupBox(self.widgetMain)
        self.groupBoxAccount.setFlat(True)
        self.groupBoxAccount.setObjectName(_fromUtf8("groupBoxAccount"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBoxAccount)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonWalletA = QtGui.QPushButton(self.groupBoxAccount)
        self.pushButtonWalletA.setEnabled(False)
        self.pushButtonWalletA.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonWalletA.setObjectName(_fromUtf8("pushButtonWalletA"))
        self.horizontalLayout_2.addWidget(self.pushButtonWalletA)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelOrderlag = QtGui.QLabel(self.groupBoxAccount)
        self.labelOrderlag.setText(_fromUtf8(""))
        self.labelOrderlag.setObjectName(_fromUtf8("labelOrderlag"))
        self.horizontalLayout_2.addWidget(self.labelOrderlag)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonWalletB = QtGui.QPushButton(self.groupBoxAccount)
        self.pushButtonWalletB.setEnabled(False)
        self.pushButtonWalletB.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonWalletB.setObjectName(_fromUtf8("pushButtonWalletB"))
        self.horizontalLayout_2.addWidget(self.pushButtonWalletB)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBoxAccount)
        self.groupBoxTrading = QtGui.QGroupBox(self.widgetMain)
        self.groupBoxTrading.setFlat(True)
        self.groupBoxTrading.setCheckable(False)
        self.groupBoxTrading.setObjectName(_fromUtf8("groupBoxTrading"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxTrading)
        self.verticalLayout.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textBrowserStatus = QtGui.QTextBrowser(self.groupBoxTrading)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserStatus.sizePolicy().hasHeightForWidth())
        self.textBrowserStatus.setSizePolicy(sizePolicy)
        self.textBrowserStatus.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.textBrowserStatus.setFont(font)
        self.textBrowserStatus.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowserStatus.setToolTip(_fromUtf8(""))
        self.textBrowserStatus.setFrameShape(QtGui.QFrame.WinPanel)
        self.textBrowserStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowserStatus.setOpenLinks(False)
        self.textBrowserStatus.setObjectName(_fromUtf8("textBrowserStatus"))
        self.verticalLayout.addWidget(self.textBrowserStatus)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonBuy = QtGui.QRadioButton(self.groupBoxTrading)
        self.radioButtonBuy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonBuy.setChecked(True)
        self.radioButtonBuy.setObjectName(_fromUtf8("radioButtonBuy"))
        self.horizontalLayout_4.addWidget(self.radioButtonBuy)
        self.radioButtonSell = QtGui.QRadioButton(self.groupBoxTrading)
        self.radioButtonSell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonSell.setChecked(False)
        self.radioButtonSell.setObjectName(_fromUtf8("radioButtonSell"))
        self.horizontalLayout_4.addWidget(self.radioButtonSell)
        self.pushButtonSize = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonSize.setObjectName(_fromUtf8("pushButtonSize"))
        self.horizontalLayout_4.addWidget(self.pushButtonSize)
        self.doubleSpinBoxBtc = QtGui.QDoubleSpinBox(self.groupBoxTrading)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxBtc.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxBtc.setSizePolicy(sizePolicy)
        self.doubleSpinBoxBtc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBtc.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxBtc.setDecimals(8)
        self.doubleSpinBoxBtc.setMaximum(999999.0)
        self.doubleSpinBoxBtc.setObjectName(_fromUtf8("doubleSpinBoxBtc"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxBtc)
        self.pushButtonPrice = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonPrice.setObjectName(_fromUtf8("pushButtonPrice"))
        self.horizontalLayout_4.addWidget(self.pushButtonPrice)
        self.doubleSpinBoxPrice = QtGui.QDoubleSpinBox(self.groupBoxTrading)
        self.doubleSpinBoxPrice.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPrice.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPrice.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxPrice.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxPrice.setDecimals(5)
        self.doubleSpinBoxPrice.setMaximum(9999.0)
        self.doubleSpinBoxPrice.setSingleStep(0.01)
        self.doubleSpinBoxPrice.setObjectName(_fromUtf8("doubleSpinBoxPrice"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxPrice)
        self.pushButtonTotal = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonTotal.setObjectName(_fromUtf8("pushButtonTotal"))
        self.horizontalLayout_4.addWidget(self.pushButtonTotal)
        self.doubleSpinBoxTotal = QtGui.QDoubleSpinBox(self.groupBoxTrading)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxTotal.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxTotal.setSizePolicy(sizePolicy)
        self.doubleSpinBoxTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTotal.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxTotal.setDecimals(5)
        self.doubleSpinBoxTotal.setMaximum(99999999.0)
        self.doubleSpinBoxTotal.setSingleStep(100.0)
        self.doubleSpinBoxTotal.setObjectName(_fromUtf8("doubleSpinBoxTotal"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTotal)
        self.pushButtonGo = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGo.setToolTip(_fromUtf8(""))
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.horizontalLayout_4.addWidget(self.pushButtonGo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEditOrder = QtGui.QLineEdit(self.groupBoxTrading)
        self.lineEditOrder.setObjectName(_fromUtf8("lineEditOrder"))
        self.horizontalLayout_8.addWidget(self.lineEditOrder)
        self.checkBoxCancelAll = QtGui.QCheckBox(self.groupBoxTrading)
        self.checkBoxCancelAll.setObjectName(_fromUtf8("checkBoxCancelAll"))
        self.horizontalLayout_8.addWidget(self.checkBoxCancelAll)
        self.pushButtonCancel = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_8.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBoxTrading)
        self.tabWidget_2 = QtGui.QTabWidget(self.widgetMain)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabWidgetOrderBook = QtGui.QWidget()
        self.tabWidgetOrderBook.setObjectName(_fromUtf8("tabWidgetOrderBook"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabWidgetOrderBook)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableBid = QtGui.QTableView(self.tabWidgetOrderBook)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableBid.sizePolicy().hasHeightForWidth())
        self.tableBid.setSizePolicy(sizePolicy)
        self.tableBid.setMinimumSize(QtCore.QSize(356, 120))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableBid.setFont(font)
        self.tableBid.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableBid.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableBid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableBid.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableBid.setProperty("showDropIndicator", False)
        self.tableBid.setAlternatingRowColors(True)
        self.tableBid.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableBid.setGridStyle(QtCore.Qt.DotLine)
        self.tableBid.setWordWrap(False)
        self.tableBid.setCornerButtonEnabled(False)
        self.tableBid.setObjectName(_fromUtf8("tableBid"))
        self.tableBid.horizontalHeader().setDefaultSectionSize(108)
        self.tableBid.horizontalHeader().setMinimumSectionSize(108)
        self.tableBid.horizontalHeader().setStretchLastSection(True)
        self.tableBid.verticalHeader().setVisible(False)
        self.tableBid.verticalHeader().setDefaultSectionSize(20)
        self.tableBid.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableBid)
        self.tableAsk = QtGui.QTableView(self.tabWidgetOrderBook)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableAsk.sizePolicy().hasHeightForWidth())
        self.tableAsk.setSizePolicy(sizePolicy)
        self.tableAsk.setMinimumSize(QtCore.QSize(356, 120))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableAsk.setFont(font)
        self.tableAsk.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableAsk.setAutoFillBackground(True)
        self.tableAsk.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableAsk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableAsk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableAsk.setProperty("showDropIndicator", False)
        self.tableAsk.setAlternatingRowColors(True)
        self.tableAsk.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableAsk.setGridStyle(QtCore.Qt.DotLine)
        self.tableAsk.setWordWrap(False)
        self.tableAsk.setCornerButtonEnabled(False)
        self.tableAsk.setObjectName(_fromUtf8("tableAsk"))
        self.tableAsk.horizontalHeader().setDefaultSectionSize(108)
        self.tableAsk.horizontalHeader().setMinimumSectionSize(108)
        self.tableAsk.horizontalHeader().setStretchLastSection(True)
        self.tableAsk.verticalHeader().setVisible(False)
        self.tableAsk.verticalHeader().setDefaultSectionSize(20)
        self.tableAsk.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableAsk)
        self.tabWidget_2.addTab(self.tabWidgetOrderBook, _fromUtf8(""))
        self.tabWidgetUserOrders = QtGui.QWidget()
        self.tabWidgetUserOrders.setObjectName(_fromUtf8("tabWidgetUserOrders"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabWidgetUserOrders)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableUserOrders = QtGui.QTableView(self.tabWidgetUserOrders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableUserOrders.sizePolicy().hasHeightForWidth())
        self.tableUserOrders.setSizePolicy(sizePolicy)
        self.tableUserOrders.setMinimumSize(QtCore.QSize(240, 110))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        self.tableUserOrders.setFont(font)
        self.tableUserOrders.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableUserOrders.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableUserOrders.setAlternatingRowColors(True)
        self.tableUserOrders.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableUserOrders.setSortingEnabled(True)
        self.tableUserOrders.setObjectName(_fromUtf8("tableUserOrders"))
        self.tableUserOrders.horizontalHeader().setDefaultSectionSize(50)
        self.tableUserOrders.horizontalHeader().setMinimumSectionSize(15)
        self.tableUserOrders.horizontalHeader().setSortIndicatorShown(True)
        self.tableUserOrders.horizontalHeader().setStretchLastSection(True)
        self.tableUserOrders.verticalHeader().setDefaultSectionSize(20)
        self.tableUserOrders.verticalHeader().setMinimumSectionSize(20)
        self.tableUserOrders.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_5.addWidget(self.tableUserOrders)
        self.tabWidget_2.addTab(self.tabWidgetUserOrders, _fromUtf8(""))
        self.tabWidgetStopOrders = QtGui.QWidget()
        self.tabWidgetStopOrders.setObjectName(_fromUtf8("tabWidgetStopOrders"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.tabWidgetStopOrders)
        self.horizontalLayout_51.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit1StopSize = QtGui.QLineEdit(self.tabWidgetStopOrders)
        self.lineEdit1StopSize.setText(_fromUtf8(""))
        self.lineEdit1StopSize.setObjectName(_fromUtf8("lineEdit1StopSize"))
        self.horizontalLayout_6.addWidget(self.lineEdit1StopSize)
        self.lineEdit2StopPrice = QtGui.QLineEdit(self.tabWidgetStopOrders)
        self.lineEdit2StopPrice.setObjectName(_fromUtf8("lineEdit2StopPrice"))
        self.horizontalLayout_6.addWidget(self.lineEdit2StopPrice)
        self.pushButton1StopAdd = QtGui.QPushButton(self.tabWidgetStopOrders)
        self.pushButton1StopAdd.setObjectName(_fromUtf8("pushButton1StopAdd"))
        self.horizontalLayout_6.addWidget(self.pushButton1StopAdd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tableStopOrders = QtGui.QTableView(self.tabWidgetStopOrders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableStopOrders.sizePolicy().hasHeightForWidth())
        self.tableStopOrders.setSizePolicy(sizePolicy)
        self.tableStopOrders.setMinimumSize(QtCore.QSize(240, 110))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        self.tableStopOrders.setFont(font)
        self.tableStopOrders.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableStopOrders.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableStopOrders.setAlternatingRowColors(True)
        self.tableStopOrders.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableStopOrders.setSortingEnabled(True)
        self.tableStopOrders.setObjectName(_fromUtf8("tableStopOrders"))
        self.tableStopOrders.horizontalHeader().setDefaultSectionSize(50)
        self.tableStopOrders.horizontalHeader().setMinimumSectionSize(15)
        self.tableStopOrders.horizontalHeader().setSortIndicatorShown(True)
        self.tableStopOrders.horizontalHeader().setStretchLastSection(True)
        self.tableStopOrders.verticalHeader().setDefaultSectionSize(20)
        self.tableStopOrders.verticalHeader().setMinimumSectionSize(20)
        self.tableStopOrders.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.tableStopOrders)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBoxActivateStopLossBot = QtGui.QCheckBox(self.tabWidgetStopOrders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxActivateStopLossBot.sizePolicy().hasHeightForWidth())
        self.checkBoxActivateStopLossBot.setSizePolicy(sizePolicy)
        self.checkBoxActivateStopLossBot.setObjectName(_fromUtf8("checkBoxActivateStopLossBot"))
        self.horizontalLayout_9.addWidget(self.checkBoxActivateStopLossBot)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.lineEdit3StopID = QtGui.QLineEdit(self.tabWidgetStopOrders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit3StopID.sizePolicy().hasHeightForWidth())
        self.lineEdit3StopID.setSizePolicy(sizePolicy)
        self.lineEdit3StopID.setObjectName(_fromUtf8("lineEdit3StopID"))
        self.horizontalLayout_9.addWidget(self.lineEdit3StopID)
        self.pushButtonStopRemove = QtGui.QPushButton(self.tabWidgetStopOrders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStopRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonStopRemove.setSizePolicy(sizePolicy)
        self.pushButtonStopRemove.setObjectName(_fromUtf8("pushButtonStopRemove"))
        self.horizontalLayout_9.addWidget(self.pushButtonStopRemove)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_51.addLayout(self.verticalLayout_3)
        self.tabWidget_2.addTab(self.tabWidgetStopOrders, _fromUtf8(""))
        self.tabWidgetTicker = QtGui.QWidget()
        self.tabWidgetTicker.setObjectName(_fromUtf8("tabWidgetTicker"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabWidgetTicker)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label1Buy = QtGui.QLabel(self.tabWidgetTicker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1Buy.sizePolicy().hasHeightForWidth())
        self.label1Buy.setSizePolicy(sizePolicy)
        self.label1Buy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1Buy.setObjectName(_fromUtf8("label1Buy"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label1Buy)
        self.lineEdit1Buy = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit1Buy.setReadOnly(True)
        self.lineEdit1Buy.setObjectName(_fromUtf8("lineEdit1Buy"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit1Buy)
        self.label2Sell = QtGui.QLabel(self.tabWidgetTicker)
        self.label2Sell.setObjectName(_fromUtf8("label2Sell"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2Sell)
        self.lineEdit2Sell = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit2Sell.setReadOnly(True)
        self.lineEdit2Sell.setObjectName(_fromUtf8("lineEdit2Sell"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit2Sell)
        self.label3Last = QtGui.QLabel(self.tabWidgetTicker)
        self.label3Last.setObjectName(_fromUtf8("label3Last"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label3Last)
        self.lineEdit3Last = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit3Last.setReadOnly(True)
        self.lineEdit3Last.setObjectName(_fromUtf8("lineEdit3Last"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit3Last)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label4Volume = QtGui.QLabel(self.tabWidgetTicker)
        self.label4Volume.setObjectName(_fromUtf8("label4Volume"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label4Volume)
        self.lineEdit4Volume = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit4Volume.setReadOnly(True)
        self.lineEdit4Volume.setObjectName(_fromUtf8("lineEdit4Volume"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit4Volume)
        self.label5High = QtGui.QLabel(self.tabWidgetTicker)
        self.label5High.setObjectName(_fromUtf8("label5High"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label5High)
        self.lineEdit5High = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit5High.setReadOnly(True)
        self.lineEdit5High.setObjectName(_fromUtf8("lineEdit5High"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit5High)
        self.label6Low = QtGui.QLabel(self.tabWidgetTicker)
        self.label6Low.setObjectName(_fromUtf8("label6Low"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label6Low)
        self.lineEdit6Low = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit6Low.setReadOnly(True)
        self.lineEdit6Low.setObjectName(_fromUtf8("lineEdit6Low"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit6Low)
        self.gridLayout_2.addLayout(self.formLayout_6, 0, 1, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label7Avg = QtGui.QLabel(self.tabWidgetTicker)
        self.label7Avg.setObjectName(_fromUtf8("label7Avg"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label7Avg)
        self.lineEdit7Avg = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit7Avg.setReadOnly(True)
        self.lineEdit7Avg.setObjectName(_fromUtf8("lineEdit7Avg"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit7Avg)
        self.label8VWAP = QtGui.QLabel(self.tabWidgetTicker)
        self.label8VWAP.setObjectName(_fromUtf8("label8VWAP"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label8VWAP)
        self.lineEdit8VWAP = QtGui.QLineEdit(self.tabWidgetTicker)
        self.lineEdit8VWAP.setReadOnly(True)
        self.lineEdit8VWAP.setObjectName(_fromUtf8("lineEdit8VWAP"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit8VWAP)
        self.gridLayout_2.addLayout(self.formLayout_5, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(50, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButtonRefreshTicker = QtGui.QPushButton(self.tabWidgetTicker)
        self.pushButtonRefreshTicker.setObjectName(_fromUtf8("pushButtonRefreshTicker"))
        self.verticalLayout_4.addWidget(self.pushButtonRefreshTicker)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(20, -1, -1, -1)
        self.formLayout_4.setSpacing(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.checkBoxAutoRefreshTicker = QtGui.QCheckBox(self.tabWidgetTicker)
        self.checkBoxAutoRefreshTicker.setObjectName(_fromUtf8("checkBoxAutoRefreshTicker"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxAutoRefreshTicker)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.spinBoxAutoRefreshTicker = QtGui.QSpinBox(self.tabWidgetTicker)
        self.spinBoxAutoRefreshTicker.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxAutoRefreshTicker.setMinimum(5)
        self.spinBoxAutoRefreshTicker.setMaximum(99999)
        self.spinBoxAutoRefreshTicker.setProperty("value", 60)
        self.spinBoxAutoRefreshTicker.setObjectName(_fromUtf8("spinBoxAutoRefreshTicker"))
        self.verticalLayout_4.addWidget(self.spinBoxAutoRefreshTicker)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 4, 1, 1)
        self.tabWidget_2.addTab(self.tabWidgetTicker, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.groupBoxLog = QtGui.QGroupBox(self.widgetMain)
        self.groupBoxLog.setFlat(True)
        self.groupBoxLog.setObjectName(_fromUtf8("groupBoxLog"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxLog)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_2.setHorizontalSpacing(12)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.checkBoxLogSystem = QtGui.QCheckBox(self.groupBoxLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogSystem.sizePolicy().hasHeightForWidth())
        self.checkBoxLogSystem.setSizePolicy(sizePolicy)
        self.checkBoxLogSystem.setChecked(True)
        self.checkBoxLogSystem.setObjectName(_fromUtf8("checkBoxLogSystem"))
        self.verticalLayout_41.addWidget(self.checkBoxLogSystem)
        self.checkBoxLogTrade = QtGui.QCheckBox(self.groupBoxLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogTrade.sizePolicy().hasHeightForWidth())
        self.checkBoxLogTrade.setSizePolicy(sizePolicy)
        self.checkBoxLogTrade.setChecked(True)
        self.checkBoxLogTrade.setObjectName(_fromUtf8("checkBoxLogTrade"))
        self.verticalLayout_41.addWidget(self.checkBoxLogTrade)
        self.checkBoxLogTicker = QtGui.QCheckBox(self.groupBoxLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogTicker.sizePolicy().hasHeightForWidth())
        self.checkBoxLogTicker.setSizePolicy(sizePolicy)
        self.checkBoxLogTicker.setChecked(True)
        self.checkBoxLogTicker.setObjectName(_fromUtf8("checkBoxLogTicker"))
        self.verticalLayout_41.addWidget(self.checkBoxLogTicker)
        self.checkBoxLogDepth = QtGui.QCheckBox(self.groupBoxLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogDepth.sizePolicy().hasHeightForWidth())
        self.checkBoxLogDepth.setSizePolicy(sizePolicy)
        self.checkBoxLogDepth.setChecked(True)
        self.checkBoxLogDepth.setObjectName(_fromUtf8("checkBoxLogDepth"))
        self.verticalLayout_41.addWidget(self.checkBoxLogDepth)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_41)
        self.textBrowserLog = QtGui.QTextBrowser(self.groupBoxLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserLog.sizePolicy().hasHeightForWidth())
        self.textBrowserLog.setSizePolicy(sizePolicy)
        self.textBrowserLog.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.textBrowserLog.setFont(font)
        self.textBrowserLog.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowserLog.setFrameShape(QtGui.QFrame.WinPanel)
        self.textBrowserLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.textBrowserLog)
        self.verticalLayout_2.addWidget(self.groupBoxLog)
        MainWindow.setCentralWidget(self.widgetMain)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionPreferences_2 = QtGui.QAction(MainWindow)
        self.actionPreferences_2.setObjectName(_fromUtf8("actionPreferences_2"))
        self.menuOptions.addAction(self.actionPreferences_2)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.doubleSpinBoxBtc, self.doubleSpinBoxPrice)
        MainWindow.setTabOrder(self.doubleSpinBoxPrice, self.doubleSpinBoxTotal)
        MainWindow.setTabOrder(self.doubleSpinBoxTotal, self.lineEditOrder)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MtGox Trading UI", None))
        self.groupBoxAccount.setTitle(_translate("MainWindow", "Account", None))
        self.pushButtonWalletA.setToolTip(_translate("MainWindow", "Push to use this value", None))
        self.labelOrderlag.setToolTip(_translate("MainWindow", "MtGox trading lag (how long it takes for an order to be executed)", None))
        self.pushButtonWalletB.setToolTip(_translate("MainWindow", "Push to use this value", None))
        self.groupBoxTrading.setTitle(_translate("MainWindow", "Trading", None))
        self.radioButtonBuy.setText(_translate("MainWindow", "Buy", None))
        self.radioButtonSell.setText(_translate("MainWindow", "Sell", None))
        self.pushButtonSize.setToolTip(_translate("MainWindow", "Recalculate size", None))
        self.pushButtonSize.setText(_translate("MainWindow", "Size", None))
        self.doubleSpinBoxBtc.setToolTip(_translate("MainWindow", "Size (in BTC)", None))
        self.pushButtonPrice.setToolTip(_translate("MainWindow", "Suggest price", None))
        self.pushButtonPrice.setText(_translate("MainWindow", "Price", None))
        self.doubleSpinBoxPrice.setToolTip(_translate("MainWindow", "Price (fiat)", None))
        self.pushButtonTotal.setToolTip(_translate("MainWindow", "Recalculate total trade worth", None))
        self.pushButtonTotal.setText(_translate("MainWindow", "Total", None))
        self.doubleSpinBoxTotal.setToolTip(_translate("MainWindow", "Total trade worth (fiat)", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go!", None))
        self.lineEditOrder.setToolTip(_translate("MainWindow", "Paste order ID here or click link above", None))
        self.lineEditOrder.setPlaceholderText(_translate("MainWindow", "Order ID", None))
        self.checkBoxCancelAll.setText(_translate("MainWindow", "All ?", None))
        self.pushButtonCancel.setToolTip(_translate("MainWindow", "Cancels the order with the specified ID", None))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel Order", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetOrderBook), _translate("MainWindow", "Order Book", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetUserOrders), _translate("MainWindow", "User Orders", None))
        self.lineEdit1StopSize.setPlaceholderText(_translate("MainWindow", "Size", None))
        self.lineEdit2StopPrice.setPlaceholderText(_translate("MainWindow", "Price", None))
        self.pushButton1StopAdd.setText(_translate("MainWindow", "Add", None))
        self.checkBoxActivateStopLossBot.setText(_translate("MainWindow", "Activate Stop Loss Bot?", None))
        self.lineEdit3StopID.setPlaceholderText(_translate("MainWindow", "Stop Order ID#", None))
        self.pushButtonStopRemove.setText(_translate("MainWindow", "Remove Stop Order", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetStopOrders), _translate("MainWindow", "Stop Orders", None))
        self.label1Buy.setText(_translate("MainWindow", "Buy", None))
        self.label2Sell.setText(_translate("MainWindow", "Sell", None))
        self.label3Last.setText(_translate("MainWindow", "Last", None))
        self.label4Volume.setText(_translate("MainWindow", "Volume", None))
        self.label5High.setText(_translate("MainWindow", "High", None))
        self.label6Low.setText(_translate("MainWindow", "Low", None))
        self.label7Avg.setText(_translate("MainWindow", "Avg.", None))
        self.label8VWAP.setText(_translate("MainWindow", "VWAP", None))
        self.pushButtonRefreshTicker.setText(_translate("MainWindow", "Refresh", None))
        self.checkBoxAutoRefreshTicker.setText(_translate("MainWindow", "Auto ?", None))
        self.spinBoxAutoRefreshTicker.setSuffix(_translate("MainWindow", " seconds", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetTicker), _translate("MainWindow", "Ticker", None))
        self.groupBoxLog.setTitle(_translate("MainWindow", "Application Log", None))
        self.checkBoxLogSystem.setText(_translate("MainWindow", "System", None))
        self.checkBoxLogTrade.setText(_translate("MainWindow", "Trade", None))
        self.checkBoxLogTicker.setText(_translate("MainWindow", "Ticker", None))
        self.checkBoxLogDepth.setText(_translate("MainWindow", "Depth", None))
        self.textBrowserLog.setToolTip(_translate("MainWindow", "Technical output", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.actionPreferences_2.setText(_translate("MainWindow", "Preferences", None))

