# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu Apr 18 03:44:56 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(760, 700)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.widgetMain = QtGui.QWidget(MainWindow)
        self.widgetMain.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMain.sizePolicy().hasHeightForWidth())
        self.widgetMain.setSizePolicy(sizePolicy)
        self.widgetMain.setObjectName(_fromUtf8("widgetMain"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widgetMain)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(-1, 4, -1, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.alltabsWidget = QtGui.QTabWidget(self.widgetMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alltabsWidget.sizePolicy().hasHeightForWidth())
        self.alltabsWidget.setSizePolicy(sizePolicy)
        self.alltabsWidget.setObjectName(_fromUtf8("alltabsWidget"))
        self.tabWidgetAccountPage1 = QtGui.QWidget()
        self.tabWidgetAccountPage1.setObjectName(_fromUtf8("tabWidgetAccountPage1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabWidgetAccountPage1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonWalletA = QtGui.QPushButton(self.tabWidgetAccountPage1)
        self.pushButtonWalletA.setEnabled(False)
        self.pushButtonWalletA.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonWalletA.setObjectName(_fromUtf8("pushButtonWalletA"))
        self.horizontalLayout.addWidget(self.pushButtonWalletA)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelOrderlag = QtGui.QLabel(self.tabWidgetAccountPage1)
        self.labelOrderlag.setText(_fromUtf8(""))
        self.labelOrderlag.setObjectName(_fromUtf8("labelOrderlag"))
        self.horizontalLayout.addWidget(self.labelOrderlag)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonWalletB = QtGui.QPushButton(self.tabWidgetAccountPage1)
        self.pushButtonWalletB.setEnabled(False)
        self.pushButtonWalletB.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonWalletB.setObjectName(_fromUtf8("pushButtonWalletB"))
        self.horizontalLayout.addWidget(self.pushButtonWalletB)
        self.alltabsWidget.addTab(self.tabWidgetAccountPage1, _fromUtf8(""))
        self.tabWidgetAuthPage2 = QtGui.QGroupBox()
        self.tabWidgetAuthPage2.setFlat(False)
        self.tabWidgetAuthPage2.setObjectName(_fromUtf8("tabWidgetAuthPage2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabWidgetAuthPage2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditKey = QtGui.QLineEdit(self.tabWidgetAuthPage2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(8)
        self.lineEditKey.setFont(font)
        self.lineEditKey.setObjectName(_fromUtf8("lineEditKey"))
        self.horizontalLayout_2.addWidget(self.lineEditKey)
        self.lineEditSecret = QtGui.QLineEdit(self.tabWidgetAuthPage2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(8)
        self.lineEditSecret.setFont(font)
        self.lineEditSecret.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.lineEditSecret.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEditSecret.setObjectName(_fromUtf8("lineEditSecret"))
        self.horizontalLayout_2.addWidget(self.lineEditSecret)
        self.pushButtonApply = QtGui.QPushButton(self.tabWidgetAuthPage2)
        self.pushButtonApply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonApply.setObjectName(_fromUtf8("pushButtonApply"))
        self.horizontalLayout_2.addWidget(self.pushButtonApply)
        self.alltabsWidget.addTab(self.tabWidgetAuthPage2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.alltabsWidget)
        self.groupBoxTrading = QtGui.QGroupBox(self.widgetMain)
        self.groupBoxTrading.setFlat(True)
        self.groupBoxTrading.setCheckable(False)
        self.groupBoxTrading.setObjectName(_fromUtf8("groupBoxTrading"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxTrading)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textBrowserStatus = QtGui.QTextBrowser(self.groupBoxTrading)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserStatus.sizePolicy().hasHeightForWidth())
        self.textBrowserStatus.setSizePolicy(sizePolicy)
        self.textBrowserStatus.setMaximumSize(QtCore.QSize(16777215, 64))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(10)
        self.textBrowserStatus.setFont(font)
        self.textBrowserStatus.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowserStatus.setToolTip(_fromUtf8(""))
        self.textBrowserStatus.setFrameShape(QtGui.QFrame.WinPanel)
        self.textBrowserStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowserStatus.setOpenLinks(False)
        self.textBrowserStatus.setObjectName(_fromUtf8("textBrowserStatus"))
        self.verticalLayout.addWidget(self.textBrowserStatus)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonBuy = QtGui.QRadioButton(self.groupBoxTrading)
        self.radioButtonBuy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonBuy.setChecked(True)
        self.radioButtonBuy.setObjectName(_fromUtf8("radioButtonBuy"))
        self.horizontalLayout_4.addWidget(self.radioButtonBuy)
        self.radioButtonSell = QtGui.QRadioButton(self.groupBoxTrading)
        self.radioButtonSell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonSell.setChecked(False)
        self.radioButtonSell.setObjectName(_fromUtf8("radioButtonSell"))
        self.horizontalLayout_4.addWidget(self.radioButtonSell)
        self.pushButtonSize = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonSize.setObjectName(_fromUtf8("pushButtonSize"))
        self.horizontalLayout_4.addWidget(self.pushButtonSize)
        self.doubleSpinBoxBtc = QtGui.QDoubleSpinBox(self.groupBoxTrading)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxBtc.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxBtc.setSizePolicy(sizePolicy)
        self.doubleSpinBoxBtc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBtc.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxBtc.setDecimals(8)
        self.doubleSpinBoxBtc.setMaximum(999999.0)
        self.doubleSpinBoxBtc.setObjectName(_fromUtf8("doubleSpinBoxBtc"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxBtc)
        self.pushButtonPrice = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonPrice.setObjectName(_fromUtf8("pushButtonPrice"))
        self.horizontalLayout_4.addWidget(self.pushButtonPrice)
        self.doubleSpinBoxPrice = QtGui.QDoubleSpinBox(self.groupBoxTrading)
        self.doubleSpinBoxPrice.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPrice.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPrice.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxPrice.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxPrice.setDecimals(5)
        self.doubleSpinBoxPrice.setMaximum(9999.0)
        self.doubleSpinBoxPrice.setSingleStep(0.01)
        self.doubleSpinBoxPrice.setObjectName(_fromUtf8("doubleSpinBoxPrice"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxPrice)
        self.pushButtonTotal = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonTotal.setObjectName(_fromUtf8("pushButtonTotal"))
        self.horizontalLayout_4.addWidget(self.pushButtonTotal)
        self.doubleSpinBoxTotal = QtGui.QDoubleSpinBox(self.groupBoxTrading)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxTotal.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxTotal.setSizePolicy(sizePolicy)
        self.doubleSpinBoxTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTotal.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxTotal.setDecimals(5)
        self.doubleSpinBoxTotal.setMaximum(99999999.0)
        self.doubleSpinBoxTotal.setSingleStep(100.0)
        self.doubleSpinBoxTotal.setObjectName(_fromUtf8("doubleSpinBoxTotal"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTotal)
        self.pushButtonGo = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGo.setToolTip(_fromUtf8(""))
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.horizontalLayout_4.addWidget(self.pushButtonGo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEditOrder = QtGui.QLineEdit(self.groupBoxTrading)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        self.lineEditOrder.setFont(font)
        self.lineEditOrder.setObjectName(_fromUtf8("lineEditOrder"))
        self.horizontalLayout_8.addWidget(self.lineEditOrder)
        self.pushButtonCancel = QtGui.QPushButton(self.groupBoxTrading)
        self.pushButtonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_8.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBoxTrading)
        self.tabWidget_2 = QtGui.QTabWidget(self.widgetMain)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabWidgetOrderBook = QtGui.QWidget()
        self.tabWidgetOrderBook.setObjectName(_fromUtf8("tabWidgetOrderBook"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabWidgetOrderBook)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableBid = QtGui.QTableView(self.tabWidgetOrderBook)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableBid.sizePolicy().hasHeightForWidth())
        self.tableBid.setSizePolicy(sizePolicy)
        self.tableBid.setMinimumSize(QtCore.QSize(240, 110))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        self.tableBid.setFont(font)
        self.tableBid.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableBid.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableBid.setLineWidth(1)
        self.tableBid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableBid.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableBid.setProperty("showDropIndicator", False)
        self.tableBid.setAlternatingRowColors(True)
        self.tableBid.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableBid.setGridStyle(QtCore.Qt.DotLine)
        self.tableBid.setWordWrap(False)
        self.tableBid.setCornerButtonEnabled(False)
        self.tableBid.setObjectName(_fromUtf8("tableBid"))
        self.tableBid.horizontalHeader().setDefaultSectionSize(110)
        self.tableBid.horizontalHeader().setMinimumSectionSize(80)
        self.tableBid.horizontalHeader().setStretchLastSection(True)
        self.tableBid.verticalHeader().setVisible(False)
        self.tableBid.verticalHeader().setDefaultSectionSize(20)
        self.tableBid.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableBid)
        self.tableAsk = QtGui.QTableView(self.tabWidgetOrderBook)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableAsk.sizePolicy().hasHeightForWidth())
        self.tableAsk.setSizePolicy(sizePolicy)
        self.tableAsk.setMinimumSize(QtCore.QSize(240, 110))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        self.tableAsk.setFont(font)
        self.tableAsk.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableAsk.setAutoFillBackground(True)
        self.tableAsk.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableAsk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableAsk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableAsk.setProperty("showDropIndicator", False)
        self.tableAsk.setAlternatingRowColors(True)
        self.tableAsk.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableAsk.setGridStyle(QtCore.Qt.DotLine)
        self.tableAsk.setWordWrap(False)
        self.tableAsk.setCornerButtonEnabled(False)
        self.tableAsk.setObjectName(_fromUtf8("tableAsk"))
        self.tableAsk.horizontalHeader().setDefaultSectionSize(110)
        self.tableAsk.horizontalHeader().setMinimumSectionSize(80)
        self.tableAsk.horizontalHeader().setStretchLastSection(True)
        self.tableAsk.verticalHeader().setVisible(False)
        self.tableAsk.verticalHeader().setDefaultSectionSize(20)
        self.tableAsk.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableAsk)
        self.tabWidget_2.addTab(self.tabWidgetOrderBook, _fromUtf8(""))
        self.tabWidgetUserOrders = QtGui.QWidget()
        self.tabWidgetUserOrders.setObjectName(_fromUtf8("tabWidgetUserOrders"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabWidgetUserOrders)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.listUserOrders = QtGui.QListView(self.tabWidgetUserOrders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listUserOrders.sizePolicy().hasHeightForWidth())
        self.listUserOrders.setSizePolicy(sizePolicy)
        self.listUserOrders.setMinimumSize(QtCore.QSize(240, 110))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        self.listUserOrders.setFont(font)
        self.listUserOrders.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.listUserOrders.setObjectName(_fromUtf8("listUserOrders"))
        self.horizontalLayout_5.addWidget(self.listUserOrders)
        self.tabWidget_2.addTab(self.tabWidgetUserOrders, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.groupBoxLog = QtGui.QGroupBox(self.widgetMain)
        self.groupBoxLog.setFlat(True)
        self.groupBoxLog.setObjectName(_fromUtf8("groupBoxLog"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxLog)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_2.setHorizontalSpacing(12)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tickerCheckBox = QtGui.QCheckBox(self.groupBoxLog)
        self.tickerCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.tickerCheckBox.setObjectName(_fromUtf8("tickerCheckBox"))
        self.gridLayout.addWidget(self.tickerCheckBox, 0, 0, 1, 1)
        self.tradesCheckBox_2 = QtGui.QCheckBox(self.groupBoxLog)
        self.tradesCheckBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.tradesCheckBox_2.setObjectName(_fromUtf8("tradesCheckBox_2"))
        self.gridLayout.addWidget(self.tradesCheckBox_2, 1, 0, 1, 1)
        self.depthCheckBox_3 = QtGui.QCheckBox(self.groupBoxLog)
        self.depthCheckBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.depthCheckBox_3.setObjectName(_fromUtf8("depthCheckBox_3"))
        self.gridLayout.addWidget(self.depthCheckBox_3, 2, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout)
        self.textBrowserLog = QtGui.QTextBrowser(self.groupBoxLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserLog.sizePolicy().hasHeightForWidth())
        self.textBrowserLog.setSizePolicy(sizePolicy)
        self.textBrowserLog.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(10)
        self.textBrowserLog.setFont(font)
        self.textBrowserLog.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowserLog.setFrameShape(QtGui.QFrame.WinPanel)
        self.textBrowserLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.textBrowserLog)
        self.verticalLayout_2.addWidget(self.groupBoxLog)
        MainWindow.setCentralWidget(self.widgetMain)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.alltabsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.doubleSpinBoxBtc, self.doubleSpinBoxPrice)
        MainWindow.setTabOrder(self.doubleSpinBoxPrice, self.doubleSpinBoxTotal)
        MainWindow.setTabOrder(self.doubleSpinBoxTotal, self.lineEditOrder)
        MainWindow.setTabOrder(self.lineEditOrder, self.lineEditKey)
        MainWindow.setTabOrder(self.lineEditKey, self.lineEditSecret)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MtGox Trading UI", None))
        self.pushButtonWalletA.setToolTip(_translate("MainWindow", "Push to use this value", None))
        self.pushButtonWalletA.setText(_translate("MainWindow", "BTC", None))
        self.labelOrderlag.setToolTip(_translate("MainWindow", "MtGox trading lag (how long it takes for an order to be executed)", None))
        self.pushButtonWalletB.setToolTip(_translate("MainWindow", "Push to use this value", None))
        self.pushButtonWalletB.setText(_translate("MainWindow", "USD", None))
        self.alltabsWidget.setTabText(self.alltabsWidget.indexOf(self.tabWidgetAccountPage1), _translate("MainWindow", "Account Balance", None))
        self.lineEditKey.setToolTip(_translate("MainWindow", "Insert your MtGox key here", None))
        self.lineEditKey.setPlaceholderText(_translate("MainWindow", "Key", None))
        self.lineEditSecret.setToolTip(_translate("MainWindow", "Insert your MtGox secret here", None))
        self.lineEditSecret.setPlaceholderText(_translate("MainWindow", "Secret", None))
        self.pushButtonApply.setToolTip(_translate("MainWindow", "Save this key / secret combination and use it", None))
        self.pushButtonApply.setText(_translate("MainWindow", "Apply", None))
        self.alltabsWidget.setTabText(self.alltabsWidget.indexOf(self.tabWidgetAuthPage2), _translate("MainWindow", "Authentication", None))
        self.groupBoxTrading.setTitle(_translate("MainWindow", "Trading", None))
        self.radioButtonBuy.setText(_translate("MainWindow", "Buy", None))
        self.radioButtonSell.setText(_translate("MainWindow", "Sell", None))
        self.pushButtonSize.setToolTip(_translate("MainWindow", "Recalculate size", None))
        self.pushButtonSize.setText(_translate("MainWindow", "Size", None))
        self.doubleSpinBoxBtc.setToolTip(_translate("MainWindow", "Size (in BTC)", None))
        self.pushButtonPrice.setToolTip(_translate("MainWindow", "Suggest price", None))
        self.pushButtonPrice.setText(_translate("MainWindow", "Price", None))
        self.doubleSpinBoxPrice.setToolTip(_translate("MainWindow", "Price (in USD)", None))
        self.pushButtonTotal.setToolTip(_translate("MainWindow", "Recalculate total trade worth", None))
        self.pushButtonTotal.setText(_translate("MainWindow", "Total", None))
        self.doubleSpinBoxTotal.setToolTip(_translate("MainWindow", "Total trade worth (in USD)", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go!", None))
        self.lineEditOrder.setToolTip(_translate("MainWindow", "Paste order ID here or click link above", None))
        self.lineEditOrder.setPlaceholderText(_translate("MainWindow", "Order ID", None))
        self.pushButtonCancel.setToolTip(_translate("MainWindow", "Cancels the order with the specified ID", None))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel Order", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetOrderBook), _translate("MainWindow", "Order Book", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetUserOrders), _translate("MainWindow", "User Orders", None))
        self.groupBoxLog.setTitle(_translate("MainWindow", "Application Log", None))
        self.tickerCheckBox.setText(_translate("MainWindow", "Ticker", None))
        self.tradesCheckBox_2.setText(_translate("MainWindow", "Trades", None))
        self.depthCheckBox_3.setText(_translate("MainWindow", "Depth", None))
        self.textBrowserLog.setToolTip(_translate("MainWindow", "Technical output", None))

